# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - botharm_controller
    - leftarm_controller
    - rightarm_controller

  botharm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l1
      - l2
      - l3
      - l4
      - l5
      - r1
      - r2
      - r3
      - r4
      - r5
    action_ns: follow_joint_trajectory
    default: true
  leftarm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l1
      - l2
      - l3
      - l4
      - l5
  rightarm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r1
      - r2
      - r3
      - r4
      - r5